feat: upload the wysiwyg images to a public url
ArkEcosystem/laravel-ui pull request #363
Opened 2021-03-17 20:21 UTC by alfonsobries

## Summary

The markdown editor now uploads the images to a public URL instead of adding the full base64 data.

A few remarks:

1. The route for uploading images will need a logged user so if we ever add this editor for a guest user it will not work
2. That also means that the route for uploading images is subject to expire due to the csrf token. For now, I'm adding just an alert to inform the user that needs to refresh the page to continue uploading images but if this becomes a problem we will need to find a way to refresh the csrf token without refreshing the page. Thinks there are a couple of packages there that helps with that.

### How to test

Just add the "full" value to the toolbar attribute to the markdown editor, I personally tested by temporary changing that value on the `resources/views/livewire/update-profile.blade.php ` on markestquare and then opening the page to edit the profile

```html
<x-ark-markdown
            name="about"
            toolbar="full"
            height="350px"
            :chars-limit="1000"
            hide-label
            :show-reading-time="false"
        />
```

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] I provided a screenshot of my changes to the component _(if applicable)_
-   [x] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [x] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-03-18 10:14 UTC, ItsANameToo requested changes

2021-03-18 10:14 UTC, ItsANameToo commented on src/Http/Controllers/WysiwygControlller.php
> +            'wysiwyg',
can you make this folder configurable? it's not really `wysiwyg` and will differ between ark.io and later MSQ for example

2021-03-18 11:11 UTC, ItsANameToo commented
@alfonsobries why was the CSRF token necessary? the `app.blade.php` file already includes one 🤔

2021-03-18 13:36 UTC, alfonsobries commented
> @alfonsobries why was the CSRF token necessary? the `app.blade.php` file already includes one 🤔 

Do you mean why it is needed as an optional parameter? If so is because I cannot say for sure that the csrf token will be in the template so it's a way to make it more reusable 

If you mean why is needed at all it is because the ajax request needed it for passing the different request  protections

2021-03-18 14:17 UTC, ItsANameToo commented
> > @alfonsobries why was the CSRF token necessary? the `app.blade.php` file already includes one 🤔
> 
> Do you mean why it is needed as an optional parameter? If so is because I cannot say for sure that the csrf token will be in the template so it's a way to make it more reusable
> 
> If you mean why is needed at all it is because the ajax request needed it for passing the different request protections

more why it's needed at all if we always have a csrf token in the `app.blade.php` template that all our pages extend from

2021-03-18 14:21 UTC, alfonsobries commented
Because the Ajax request that upload the images doesn't send the csrf token by default I need to explicitly add it to the request headers

2021-03-18 14:22 UTC, alfonsobries commented
Because the Ajax request that upload the images doesn't send the csrf token by default I need to explicitly add it to the request headers

2021-03-18 16:17 UTC, alfonsobries commented
@ItsANameToo to clarify I need to grab that token from somewhere to eventually add it to the ajax request here https://github.com/ArkEcosystem/laravel-ui/pull/363/files#diff-dac9b0f2931b8e271ec25a04abeb3a74aea13892eadd2f4031debbb57eabaf7cR109

2021-03-29 15:48 UTC, ItsANameToo commented
@alfonsobries can you remove the csfr token being passed as a property? it will always be available on the page in the meta tag, if not then it's up to the user to fix that and not the component

2021-03-29 15:52 UTC, alfonsobries commented
@ItsANameToo done

2021-03-29 16:20 UTC, ItsANameToo commented on src/UserInterfaceServiceProvider.php
> +            Route::post('upload-image', [WysiwygControlller::class, 'uploadImage'])->name('wysiwyg.upload-image')->middleware('web');
can you add `auth` middleware to this? the editor is only used by logged in people at the moment anyway

2021-03-30 08:24 UTC, ItsANameToo approved these changes

2021-03-30 08:24 UTC, merged