fix: properly handle null values when validating markdown
ArkEcosystem/laravel-ui pull request #521
Opened 2021-06-21 20:09 UTC by alfonsobries

## Summary

https://app.clickup.com/t/mvde3k

Fixed an exception that occurs when the value passed to the validator is null and regression test

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] I provided a screenshot of my changes to the component _(if applicable)_
-   [x] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-06-22 08:32 UTC, ItsANameToo requested changes
failing test @alfonsobries

2021-06-25 08:35 UTC, ItsANameToo commented
still failing test @alfonsobries :bleh:

2021-06-27 14:49 UTC, alfonsobries commented
@ItsANameToo ✅

(The issue was related to the typing that doesn't work on php 7.4 so I updated github actions to use php8, as an alternative I can just remove the typing)

2021-06-28 09:46 UTC, ItsANameToo approved these changes

2021-06-28 14:10 UTC, merged