fix: update classes to break long external links
ArkEcosystem/laravel-ui pull request #534
Opened 2021-06-28 22:28 UTC by alfonsobries

## Summary

Adjusted the CSS classes for the long links on the markdown to ensure the lines are broken if doesn't fit on the screen:

## Before:
![image](https://user-images.githubusercontent.com/17262776/123711408-0e9dfa80-d836-11eb-9dfd-ccbdc1e88e71.png)

## After
![image](https://user-images.githubusercontent.com/17262776/123711448-1e1d4380-d836-11eb-94c4-2f1a4cf9d8ce.png)

## Test

To test merge this on msq and adds some long-length links on the project info section

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [x] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-06-29 09:41 UTC, alexbarnsley commented
the link still seems to get too close to the edge 🤔

2021-06-29 09:42 UTC, alexbarnsley requested changes
above comment

2021-06-29 15:33 UTC, alfonsobries commented
@alexbarnsley fixed

2021-06-30 13:11 UTC, ItsANameToo approved these changes

2021-06-30 13:11 UTC, merged