chore: improve disabled state
ArkEcosystem/laravel-ui pull request #595
Opened 2021-08-04 10:08 UTC by leMaur

## Summary
https://app.clickup.com/t/pnabvn

This PRs adds `disabled` state for "table view-options" and "dropdown".

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [x] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

2021-08-04 20:37 UTC, alexbarnsley requested changes

2021-08-04 20:37 UTC, alexbarnsley commented on resources/views/dropdown.blade.php
> +            @if($disabled) disabled @endif
could this be an if/else?

```
@unless($disabled)
	@click="{{ $dropdownProperty }} = !{{ $dropdownProperty }}" 
@else
	disabled
@endunless
```

or vice versa

2021-08-04 20:37 UTC, alexbarnsley commented on resources/views/tables/view-options.blade.php
> +        @if ($disabled) disabled @endif
similar to above? 🤔

2021-08-04 20:37 UTC, alexbarnsley commented on resources/views/tables/view-options.blade.php
> +        @if ($disabled) disabled @endif
similar to above? 🤔

2021-08-05 10:50 UTC, ItsANameToo approved these changes

2021-08-05 10:51 UTC, ItsANameToo commented
@leMaur conflict

2021-08-05 10:52 UTC, ItsANameToo approved these changes

2021-08-06 08:15 UTC, merged