fix: normalize external link component
ArkEcosystem/laravel-ui pull request #612
Opened 2021-08-12 18:17 UTC by alfonsobries

## Summary

https://app.clickup.com/t/u3rqze

Fixes some differences between external links.

**Notes:**
1. Part of the problem is that the markdown parser removes the `span` inside the external links leaving an extra blank space, so:
  - I am removing the `span` from the component to ensure that the component renders the same when adding manually or added through the markdown parser.
  - I am adding some `` comments as a workaround to prevent any extra space left when parsed (the "comment" is removed on the parser but not when added manually).
![Screen Shot 2021-08-12 at 13 08 31](https://user-images.githubusercontent.com/17262776/129247043-a29c5307-0cec-4ca0-ab07-020de6de27b6.png)

2. Fixed a regression with long links not breaking again (fixed on the screenshot)
![image](https://user-images.githubusercontent.com/17262776/129247279-63a31143-798c-415d-af28-5febf5a2d52e.png)

3. Removes some attributes that don't make sense like the `inline` (all links are inline) and the `allowWrap` and checked all the projects that are affected (ark.io and msq are the only ones) 

## To test

Merge this on the msq PR and on the ark.io PR, recompile assets and compare the links on articles, user profile, and basically, everything that is dynamic and the links added manually like the lins on the footer on ark.io or the social network links on the projects.

Ensure to review every possible link you can find (search for `<x-ark-external-link` references)
 
 
## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [x] I provided a screenshot of my changes to the component _(if applicable)_
-   [x] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [x] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-08-19 07:56 UTC, leMaur commented
@alfonsobries I've tested thoroughly on MSQ and ARK.io and I didn't find any issue 👍🏼

2021-08-19 07:56 UTC, leMaur approved these changes

2021-08-20 15:01 UTC, ItsANameToo requested changes

2021-08-20 15:01 UTC, ItsANameToo commented on resources/views/external-link.blade.php
> +    class="{{ $class }} {{ $breakAll ? 'break-all' : 'break-words' }} "
would make it part of the class property instead, so it has `link font-semibold inline break-words`. That way if you really need `break-all` you can pass it as class anyway without needing a special property for it

2021-08-20 16:43 UTC, alfonsobries commented
@ItsANameToo ✅

2021-08-24 12:36 UTC, ItsANameToo commented
See comment on MSQ PR @alfonsobries

2021-08-24 14:18 UTC, alfonsobries commented
@ItsANameToo mm... apparently only happens on links that have text on the right side, fixed by adding the underline to the span on external links (to prevent the underline on the icon).

✅

2021-08-24 14:30 UTC, ItsANameToo approved these changes

2021-08-24 14:32 UTC, merged