fix: handle opening external links when using mouse scroll click
ArkEcosystem/laravel-ui pull request #628
Opened 2021-08-27 19:41 UTC by alfonsobries

## Summary

As the title says

https://app.clickup.com/t/yy957w

To test: merge this on msq and try to open an external link with the mouse scroll

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-08-30 10:20 UTC, ItsANameToo requested changes
not working when used on msq with `yarn prod`

2021-08-30 10:20 UTC, ItsANameToo requested changes

2021-08-30 10:20 UTC, ItsANameToo commented on resources/views/external-link-confirm.blade.php
> +            }
this probably needs a `;` to avoid issues when minimized

2021-08-30 10:28 UTC, ItsANameToo commented on resources/views/external-link-confirm.blade.php
> +                // The rest of the buttons are handled bu the `click` event.
```suggestion
                // The rest of the buttons are handled by the `click` event.
```

2021-08-30 10:28 UTC, ItsANameToo commented on resources/views/external-link-confirm.blade.php
> +            link.addEventListener('mousedown', (e) => {
issue with `mousedown` is that it triggers immediately, and not after "clicking". Wouldn't something like https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event be more suitable to keep it in line with the regular click handling? 🤔

2021-08-30 10:34 UTC, ItsANameToo commented on resources/views/external-link-confirm.blade.php
> +            link.addEventListener('mousedown', (e) => {
nvm no full support for that event in all browsers :sadup:

still think it feels a bit odd having the middle click open it immediately as opposed to the regular click, will check for alternatives

2021-08-30 15:12 UTC, alfonsobries commented
@ItsANameToo the auxclick event did the trick, the docs say that it not works on safari but tested and it works fine (maybe doesnt work on safari but safari handles the middle click differently)

Tested of firefox, brave safari  and Microsoft edget (for mac)

2021-08-31 08:17 UTC, ItsANameToo approved these changes

2021-08-31 08:25 UTC, merged