refactor: remove shadows from buttons
ArkEcosystem/laravel-ui pull request #636
Opened 2021-09-07 21:29 UTC by alfonsobries

## Summary

https://app.clickup.com/t/11m2zd1

Removes the shadows from the buttons, the ticket mentions explorer but applies to all projects

![image](https://user-images.githubusercontent.com/17262776/132413112-021646d4-9fd0-4684-a6c8-f83607aefec4.png)

![image](https://user-images.githubusercontent.com/17262776/132413345-49131fce-7c93-4b42-accc-c9f3fb79874d.png)

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [X] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-09-08 07:34 UTC, ItsANameToo requested changes

2021-09-08 07:34 UTC, ItsANameToo commented on resources/assets/css/_buttons.css
> -    @apply bg-theme-primary-700 shadow-button-primary;
can also remove the styling from the tailwind config file if we get rid of it for the buttons

2021-09-08 08:08 UTC, ItsANameToo commented on resources/assets/css/_buttons.css
> -    @apply bg-theme-primary-700 shadow-button-primary;
there's also other parts that use `shadow-button-primary`, e.g. the markdown editor styling to mimic the regular buttons for modals

2021-09-09 15:17 UTC, alfonsobries commented
@ItsANameToo ✅

2021-09-14 13:03 UTC, alexbarnsley approved these changes

2021-09-14 14:27 UTC, ItsANameToo approved these changes

2021-09-14 14:27 UTC, merged