refactor: use conditional classes for inputs sub components
ArkEcosystem/laravel-ui pull request #652
Opened 2021-09-16 09:09 UTC by Highjhacker

## Summary

https://app.clickup.com/t/rag8g9

Concern all blade files located within inputs/includes

## Checklist

-   [x] I checked my UI changes against the design and there are no notable differences
-   [x] I checked my UI changes for any responsiveness issues
-   [x] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I provided a screenshot of my changes to the component _(if applicable)_
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

2021-09-16 21:11 UTC, alexbarnsley requested changes
I tested this on Nodem. Notice how the `Username` label isn't red when shown for this branch. I suspect it's not being picked up or potentially passed in correctly with `$errors`? It may not have been noticeable before when using the `@error` directive 🤔 

this branch:
![image](https://user-images.githubusercontent.com/8069294/133685508-00e357d7-2317-419c-a006-184a8d9e2f46.png)

existing release:
![image](https://user-images.githubusercontent.com/8069294/133685548-e1b26d26-7447-4a8f-84dc-c022776aaa55.png)

2021-09-16 21:20 UTC, alexbarnsley commented on resources/views/inputs/includes/input-label.blade.php
> +        'input-label--error' => $errors->has('name'),
```suggestion
        'input-label--error' => $errors->has($name),
```

2021-09-16 21:23 UTC, alexbarnsley commented on resources/views/inputs/includes/input-label.blade.php
> +        'input-label--error' => $errors->has('name'),
When I changed to this the `Username` label had the error class again, as it should

2021-09-20 08:38 UTC, ItsANameToo approved these changes

2021-09-20 08:45 UTC, merged